export enum allRoutes  {
    homePage = "/",
    about = "/about",
    inbox = "/inbox",
    messages = "/messages",
    pricing = "/pricing",
    features = "/features",
    gallery = "/gallery",
    team = "/team",
    dashboard = "/dashboard",
    orders = "/orders",
    schedules = "/schedules",
    analytics = "/analytics",
    settings = "/settings",
    news = "/news",
}